### ISSUE TITLE
Row select support in tables is missing features

### ISSUE THREAD

**Issue by stevemandl** [bootstrap-vue-next/bootstrap-vue-next#1251]
The bootstrap-vue feature for row select support is partly documented here: https://bootstrap-vue.org/docs/components/table#row-select-support

- When a row is selected, the 'selected' field should display a check iff the row is selected. Currently the check is always displayed, and only the class of the check changes (text-primary is added) when the row is selected.

- The checkbox field should only display if the fields array contains a 'selected' field, and it should display in the column location corresponding to the position in the fields array. Currently the select cell always displays in the first column, unless the select-head prop is false in which case it does not display.

**Comment by devhus** [comment]
In this https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1262 PR, You will be able to apply your own selection styling using the mentioned css selectors.
About the "selected" field, I didn't like the way BV2 doing it and how its limiting you from using "selected" named field. Keep in mind that it is very rare to find someone who wants the selection box in the center of the table and i don't think it worth the effort

**Comment by stevemandl** [comment]
@devhus 
Thanks for the thoughtful reply.
I agree a checkbox in the center of the table is rare. I have a need to put the selection box at the end of the table, and tried to follow the BV2 docs to see if it would work. I ended up coding my own selection box in a column at the end, and if I need to keep my custom table so be it.
   Is there is an easy way in css to make the checkbox appear at the end of the selected row using the selection styling you mentioned? From what I saw it looks like we will be able to change the way the checkbox looks, or how the row is styled, but adding a checkbox to the last column seems tricky or impossible in css.

**Comment by VividLemon** [comment]
So, based on my changes there are a couple of things to note. 

The major note is that the "row-selected" event is different than the BV version. Namely that it does not emit the array. 

The second major note is that the functionality for row selection has changed. Now instead you can (in addition to the other methods, exposed and otherwise) use a v-model. This allows for more flexible selection. 

The documentation on this is yet to be written, and its in an unreleased state. I'm going to keep "row-selected" event as emitting only its row, as I believe it makes more logical sense for a "row-selected" to emit only that "selected row", given all the new options you have for selection (simply `v-model:selectedItems` should give you the same result, with some minor modification [you won't need the event])

In the meantime, I'm going to close this, docs to come
