### ISSUE TITLE
`type` of `Navbar` does not control color as it is supposed to

### ISSUE THREAD

**Issue by nathanielwarner** [bootstrap-vue-next/bootstrap-vue-next#1507]
According to [docs](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/ad587341290cdb730d69bfda44253e5f6523738b/apps/docs/src/docs/components/navbar.md?plain=1#L92C1-L92C1), the `type` attribute of `Navbar` should control whether the text is dark or light. It doesn't work though, and it's necessary to instead set `data-bs-theme`. We could fix this either by updating the docs, or changing the `Navbar` so that it internally sets `data-bs-theme` based on `type`.

**Comment by VividLemon** [comment]
`type` is removed. Feel free to update the docs. The suggested way to fix it is to use the color mode utilities, either useColorMode, or vBColorMode, or raw.

**Comment by dwgray** [comment]
@nathanielwarner I have PR #1511 up to update the docs to use data-bs-theme.  This makes the dark-themed navbars in the samples usable again.  I did this because it was blocking the smaller doc fix for #1510 and because it seems like the most straight-forward solution.

I think there is an argument to re-instate type to make migration easier, but I figured doing the easier thing first is generally better.
