### ISSUE TITLE
Global Options(nuxt): use NuxtLink for BLink

### ISSUE THREAD

**Issue by thehouseisonfire** [bootstrap-vue-next/bootstrap-vue-next#1569]
I'm working on an app with routing and a lot of assets loading (primarily images) and Nuxt 3 documentation mention their optimized components for those use cases. I'm guessing the answer is no for NuxtImg specifically since its a separate module, but would Bootstrap-vue-next/nuxt happen to use those for BLink and BImg under the hood?

**Comment by VividLemon** [comment]
The `Bootstrap-vue-next/nuxt` package doesn't do anything to the behavior of the code. The answer is no to both questions. It could be possible to modify the behavior in the future. 

Hypothetically, if (_when_) "global options" are implemented it would be possible to make a change that converts blinks to use nuxtlink. NuxtImg is probably not possible since it would require a third party "unofficial" dependency. (Unofficial in that it is not apart of the core Nuxt package)

**Comment by VividLemon** [comment]
Note to self: after global options exist, make NuxtLink the default. NuxtImg is likely not possible (Ig BImg could be a dynamic component... Not sure how well that would work)

**Comment by VividLemon** [comment]
In neither case is the nuxt module able to know that NuxtImg exists (that module is installed) or if Nuxt is using a routing system (the router code is treeshaken off if the pages dir doesn't exist... or some dir, idk what it is)

So since _we_ can't know these values, it's up to the user to define them.

The way you'd do this is

```ts
export default defineNuxtConfig({
  modules: ['../src/module'],
  css: ['bootstrap/dist/css/bootstrap.min.css'],
  bootstrapVueNext: {
    plugin: {
      components: {
        BLink: {
          routerComponentName: 'NuxtLink',
        },
        BImg: {
          tag: 'NuxtImg',
        },
      },
    },
  },
})
```
