### ISSUE TITLE
bootstrap-vue-next should depend on vue version supported by bootstrap-vue

### ISSUE THREAD

**Issue by kalekseev** [bootstrap-vue-next/bootstrap-vue-next#1646]
### Describe the bug

Currently bootstrap-vue-next depends on vue ^3.3.8, bootstrap-vue doesn't work with vue 3.3.5+ because of https://github.com/bootstrap-vue/bootstrap-vue/issues/7181

### Reproduction

https://github.com/bootstrap-vue/bootstrap-vue/issues/7181

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kalekseev** [comment]
We have big project currently running on bootstrap-vue and would like to migrate it to bootstrap-vue-next, right now we have bv and bvn installed together and run on the same version of vue that means we can develop for both version simultaneously. But BVN specifies vue peer dependency as
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/7743a5543664bfb1dc76abe0177e2503f480c8eb/packages/bootstrap-vue-next/package.json#L45
Would be better to have it as `^3.3` and be sure that BVN will support v3.3 for some time.

**Comment by xvaara** [comment]
BVN requires 3.3.6 because teleport bug fixes.

**Comment by xvaara** [comment]
@kalekseev you could maybe override the version with:
```
"resolutions": {
    "vue": "3.3.4"
}
```
in your package.json.

What are you missing from BVN to fully migrate?

**Comment by VividLemon** [comment]
> BVN requires 3.3.7 because teleport bug fixes.

It's not technically a requirement for us to have 3.3.7. If someone where to want to stay on a lower version and experience that bug, that's on them. In such a case, I'd imagine some false flags of bug reports, but that's still not our problem, just a minor bloat of issues. 

However, that is an argument _for_ lowering the package version, which I am still against. In my subjective feeling, I don't agree with marrying the package versions together. Like I said, they are independent projects, though related. It is my belief that the development of this project shouldn't be slowed by a project that [will likely never see such an update]

I agree that the best outcome is to probably accelerate the progress to full migration. Or simply ignore the peer dependency error, or overwrite the peer dependency. There is nothing inherently wrong about a lower Vue version, you just might experience some of the issues that were fixed in the upper versions. Regardless on whether or not we explicitly support them, they should still be usable

That being said, the dependencies get changed every now and again, this is only because the package is in pre-1.0. Once 1.0 does get released, the peer dependency should likely never change (depending on the timing, it will be 3.4 [because of the reactivity improvements]). But it depends on whatever the version Vue is at when the package is 'done'
