### ISSUE TITLE
BFormSelect modelValue typing should allow boolean (or Booleanish)

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1671]
### Describe the bug

The current type of modelValue is `string | unknown[] | Record<string, unknown> | number | null`

But things work just fine if you use a boolean (except for the fact that typescript complains):

```
<template>
  <BFormSelect v-model="sortDesc" size="sm" class="w-25">
    <option :value="false">Asc</option>
    <option :value="true">Desc</option>
  </BFormSelect>
</template>

<script setup lang="ts">
import {ref, type Ref} from 'vue'

const sortDesc: Ref<boolean | null> = ref(null)
</script>
```

I believe the type should be `string | unknown[] | Record<string, unknown> | number | Booleanish | null`

I am happy to fix this, but could use some guidance on the interaction of `useBooleanish` and `useVModel` - the only way I see to make this work is just not to use `useVModel` and instead directly access the modelValue and call emit, but as usual I'm probably missing something...

### Reproduction

see above

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dwgray** [comment]
@xvaara can you tell me why using a boolean here is acceptable rather than a Booleanish?  Had I known that boolean was acceptable in this case, I could have fixed it myself...

**Comment by VividLemon** [comment]
Type string is inclusive of "true"| " false". Resolving the value seems strange in the context of a select, but idk

**Comment by dwgray** [comment]
> Type string is inclusive of "true"| " false". Resolving the value seems strange in the context of a select, but idk

Thanks @VividLemon, that makes sense.  FYI the example that caused me to look at this was https://bootstrap-vue.org/docs/components/table#complete-example from the BVS legacy documentation.

**Comment by VividLemon** [comment]
I suppose literal union "hacks" could enhance these. But its fairly underused throughout the lib, and I'm not sure how useful it is in most places https://stackoverflow.com/questions/61047551/typescript-union-of-string-and-string-literals

**Comment by VividLemon** [comment]
> Is this original to you, or did you pull it from someplace

The term Booleanish is used in @vue/runtime-dom. Similarly, Numberish is used (which is apart of my outstanding PR). The goal of adding an empty string to the Booleanish type was to fix an issue with the Vue boolean resolver https://vuejs.org/guide/components/props.html#boolean-casting . Boolean values are close to the implementation of basic HTML, where `disabled` is implicitly `true` and the absence of `disabled` is implicitly `false`. The issue comes when you mix boolean and strings together, you get different results with it not being implicit. 

That being said, there is a line that I missed in that documentation originally: 

> However, there is an edge when both String and Boolean are allowed - the Boolean casting rule only applies if Boolean appears before String:

So, the `''` being an option isn't something that needs to remain. -- In my current PR, I have changed the order to have boolean be first, thus fixing this. But have not removed `''`, I will likely do that sometime soon. 

The issue is that `<BFormInput disabled />` makes the disabled prop become an empty string, not very useful. However, by removing the empty string and placing boolean first, disabled will evaluate to `true`. 

So, in summary, it is a creation of mine, yes. Although the actual resolving of "true"/"false" to true/false is somewhat of a divergence that I feel should remain, as technically `<BFormInput disabled="false" />` should technically make HTML disabled become implicitly true, as obviously it exists. I suppose it could be removed outright, to align closer to HTML and Vue, but I added it to make it a bit more shorter than `:disabled="false" => disabled="false"`. Regardless of it only being a difference of `:`. Though, why Vue has this Booleanish type, but doesn't discriminate between `"true" & "false"` is a bit strange to me (Regardless of the HTML spec, its confusing on why they have it if they're not going to use it. "false" is still implicitly true). But removing it now seems like a bit of a bad step, considering how often Booleanish is used overall, regardless on if I have come around to the idea of removing it.

**Comment by VividLemon** [comment]
> regardless on if I have come around to the idea of removing it

(https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/96a4816419551116ccbe808cf57ff72358f0dda7)

**Comment by dwgray** [comment]
Thanks - I appreciate the comprehensive explanation.  I hope it's clear that I'm just trying to learn (and hopefully help by applying that learning to fixes or documentation moving forward).  I'll hold off on doing anything related to Booleanish, though, until things have settled into some kind of stable state - skimming through your current PR, there's a lot in motion :-)

**Comment by VividLemon** [comment]
> skimming through your current PR, there's a lot in motion :-)

It may look large, but the majority of the work is just wrapping array and objects in Readonly. Pretty straightforward stuff. In addition to trying to make the lib more "functional", in that it wont mutate arrays and objects, its also to make a commitment that we wont arbitrarily mutate props of type array or object (you can mutate nested properties of non-primitives in Vue 3)

**Comment by dwgray** [comment]
Got it.  I mostly meant that I don't think it makes sense for me to muck around in anything related to Booleanish (including documentation) until you've settled on its behavior.
