### ISSUE TITLE
BTable: Sorting not working correctly with negative values

### ISSUE THREAD

**Issue by TejasBavaskar** [bootstrap-vue-next/bootstrap-vue-next#1863]
### Describe the bug

**BTable sorting works incorrectly when the column data contains negative values.**
Example: 
In the provided stackblitz link, the `marks` column has negative values. If the column is sorted in the ascending order then
**Current output:** `-40, -45, 21, 38, 89, 89`
**Expected output:** `-45, -40, 21, 38, 89, 89`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hntimd?file=src%2Fcomponents%2FHelloWorld.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
This isn't a bvn issue. It's an issue with localeCompare in js. 

localeCompare with {numeric: true} treats negative numbers as strings rather than numeric values. 

If you want to take over the sorting manually, you can use the `comparer` value in the sortby

https://stackblitz.com/edit/vitejs-vite-dbmwxb?file=src%2Fcomponents%2FHelloWorld.vue ie `comparer: (a, b) => Number.parseFloat(a) - Number.parseFloat(b),`
