### ISSUE TITLE
How can I remove unnecessary input-group wrap and browserLabel in BFormFile?

### ISSUE THREAD

**Issue by waiyanmintun** [bootstrap-vue-next/bootstrap-vue-next#1927]
When I upgraded from ^0.16.1 to ^0.19.0, BFormFile was wrapped in input-group and show 'Choose' label which make undesired effect. I think wrapping in input-group is not necessary as we can use b-input-group when necessary.

Working fine in 0.16.1
![Screenshot 2024-05-30 at 12 37 27 PM](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/43596105/b735f379-1cd2-4d18-8396-a15956846467)

Bricked after upgraded to 0.19.0
![Screenshot 2024-05-30 at 12 37 35 PM](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/43596105/f85ff124-8cd5-4795-a802-85dbfc6541c0)

**Comment by xvaara** [comment]
you can remove the label by adding placement="none" for now. I'll create a no-group prop or something like that.

@VividLemon I find the BFormFile component/props to be little confusing. 

- placement? of what? I know by code that it's start | end, but that doesn't follow the rtl convention, it's named weirdly. 
- The css doesn't work in darkmode, why do we even need to correct bootstrap, can't we just use it's css? 
- Why is there a random -2px margin?
- The current puts "Choose" there which isn't localised by the browser, so why are we overriding the browser default?

many of these changes were in #1797
comment if those are needed, otherwise I'll throw them to the trash from the component. And do I look at #1213 at the same time?

**Comment by waiyanmintun** [comment]
@xvaara 
Thank you for your kind reply.
I'll be waiting till it get fixed or modified with new props.
