### ISSUE TITLE
BDropdown changes v0.20.0

### ISSUE THREAD

**Issue by JagoEFP** [bootstrap-vue-next/bootstrap-vue-next#1936]
**What you are trying to do.** A clear and concise description of what you want to happen.

Hi, the new version v0.20.0 makes some changes to BDropdowns - what do they do? I've been looking through the code and I'm not sure what is going on - only that after the update I have some issues rendering my components contents/items, v0.19 had some issues but not this. I need to wrap my BDropdowns with `<ClientOnly>` tags now to get them to render their contents. Any input is appreciated! Many thanks.

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.

Wrapping my BDropdowns in  `<ClientOnly>` tags which isn't ideal. Needed for page reloads.

**Any error messages you are getting.** If any, please list the errors you are getting.

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/152709333/a50ca120-6216-4b49-9490-994cab32ae4d)

This is thrown when clicking on the dropdown.

**Environment (please complete the following information):**

- OS: linux Ubuntu v22.04
- Package Version: 0.20.0
- Npm/Yarn/Pnpm/Bun Version: yarn v1.22.19

**Comment by xvaara** [comment]
@JagoEFP not 100% since no reproduction, but try setting teleport-to="#teleports" if you're using nuxt (if not create a div with id teleports to body)

**Comment by ujex256** [comment]
I am in the same situation. Enclosing it in <ClientOnly> tags or adding teleport-to=“#teleports” worked correctly.

**Comment by VividLemon** [comment]
@xvaara What do you think would have caused this issue?

It's important in SSR contexts to provide a stable teleport target. This is why nuxt added it in their release. 

I initially added it to the nuxt module for global configuration to have it teleport to this location, but in relation to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1898 it wasn't able to inherit the style since its location in the dom was not a child element... I suppose if we were able to tell if a close parent had this class, we could selectively add it to the class list of the element, then automatically provide the stable teleport target that we need for our Teleport usage

**Comment by xvaara** [comment]
I'm working on a pr that fixes a punch of nuxt ssr problems. I've run into some quite strange bugs/"features".

**Comment by prettyblueberry** [comment]
I've found same bug. I should wrap my dropdown with <ClientOnly>. I want to render the dropdown in SSR. Is there any solution? now?

**Comment by xvaara** [comment]
I think vue 3.4.35 fixed the teleport bugs, I'll need to check.
