### ISSUE TITLE
Tooltip delay is not zero by default

### ISSUE THREAD

**Issue by someonewithpc** [bootstrap-vue-next/bootstrap-vue-next#1938]
### Describe the bug

Different from BootstrapVue 2 and [the documentation](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/directives/BTooltip#delay), the default value for the `delay`  prop for the tooltip directive is `{show: 100, hide: 300}` rather than the expected `{show: 0, hide: 0}`, indirectly, [from `BPopover`](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/9241bbebdaec581c7c6dff793b586770ef46202f/packages/bootstrap-vue-next/src/components/BPopover.vue#L113). I suspect this happens because [`undefined` is defined as the default value in `BTooltip`
](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/9241bbebdaec581c7c6dff793b586770ef46202f/packages/bootstrap-vue-next/src/components/BTooltip.vue#L21), whereas it should either be `0` or `{show: 0, hide: 0}`

### Reproduction

https://stackblitz.com/edit/github-ebkywh?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
I don't remember why I picked 100/300, but it seems that bootstrap also defaults to 0. 
I find the current delay to be more userfriendly and would like to stay with that. If you move cursor over a many tooltips, it doesn't try to load everyone if you move "fast".

@VividLemon thoughts?

**Comment by someonewithpc** [comment]
> I find the current delay to be more userfriendly

I disagree. In the project I'm working, there's a sidebar with tools each with a tooltip, and with those delays it feels very laggy. I can't just override it, as I have already, but the documentation should be updated and ideally highlight the fact that it's different from the previous version and from Bootstrap

**Comment by VividLemon** [comment]
I have no strong opinions one way or the other

In terms of arbitrarily using 100/300, there is an understanding on our end that we develop this package to make things "look good" out of the box, otherwise why use the package if not to have most things done for the downstream developer 

On the other hand, there isn't a strong reason on why this specific feature is a breaking change from bv. The only reason for it is "I think it looks better"

**Comment by neilgreatorex** [comment]
It looks to me like the fix for this actually modified the wrong value:

The change was to:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/51048b22cffa7b34cde8a1b27ca4f760b6580a83/packages/bootstrap-vue-next/src/components/BTooltip/BTooltip.vue#L29

when it should've been to:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/51048b22cffa7b34cde8a1b27ca4f760b6580a83/packages/bootstrap-vue-next/src/components/BTooltip/BTooltip.vue#L27

**Comment by slbayer** [comment]
This bug is not fixed, as of 0.28.3. `delay: undefined` does not override the `delay` value in `BPopover`. The default appears still to be 100/300.
