### ISSUE TITLE
BTable: Setting Head Slot overwrites sort icon

### ISSUE THREAD

**Issue by BenediktHeinrichs** [bootstrap-vue-next/bootstrap-vue-next#1976]
### Describe the bug

We wanted to set a custom head column in a BTable that is searchable, but overwriting that slot removes the sort icon.
This was previously doable in bootstrap-vue.

### Reproduction

https://stackblitz.com/edit/github-yk2gus?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
This is by design, but I wonder if there should be a "icon-direction" slot scope

**Comment by BenediktHeinrichs** [comment]
To maybe elaborate on our problem, it's just very annoying that if I want to overwrite a head cell, that I technically need to reimplement all the sorting icon logic.  (Our use case is removable columns, so we added an x-icon that on click removes a column)

Making the icon its own slot or even separating the head slots (e.g. head-label, head-sort-icon) would be very much appreciated.

**Comment by VividLemon** [comment]
I understand why it would want to be preserved, but the idea is more-so that by changing the head slot, you are changing the entire head

**Comment by paulkirow** [comment]
I just ran into the same issue today.  It makes something relatively simple to do in bootstrap-vue a little more convoluted in bootstrap-vue-next.

The scenario I have is similar.  I have about a dozen usages in my project which separately override the head slot for different reasons (dom changes, etc.).  However, now in all those cases the sort icons are gone.

The way I see it there are a few solutions to consider to make this more simple.

1. Don't add `aria-sort="none"` to fields which have sortable=false.

This change would match the behaviour in bootstrap-vue for when aria-sort was applied.  Instead now we add `aria-sort="none"` even for fields which are not sortable.

With this change I could leave the sortAsc, sortDesc, sortDefault slots blank and reimplement icons with css.

I'm not 100% sure on the accessibility impact,  but I believe it's negligible.

3. Reissue the head slot in BTable.vue.

Something like this:
```    
<template #head()="scope">
      <slot
        name="head()"
        :label="scope.field.label"
        :column="scope.field.key"
        :field="scope.field"
        :is-foot="false"
        v-bind="{...scope}"
      >
        {{ getTableFieldHeadLabel(scope.field) }}
      </slot>
      <template v-if="isSortable && !!scope.field.sortable && props.noSortableIcon === false">
      ... sort icon slot definitions ...
```

Now using the head slot will keep the sort icons.


3. Expose the variables used to define sortAsc, sortDesc and sortDefault through the scope of the head slot.

Even if we keep the head slot the way it is,  I can't easily reimplement these svg icons because there are variables I can't access through the slot scope.  i.e. `isSortable`, `sortByModel`.

I suppose I could probably reimplement the code for these icons without those variables exposed.  I'll update this comment if I get that working

**Comment by VividLemon** [comment]
Feel free to make a PR to which the head slot does not overwrite the sort icons
