### ISSUE TITLE
Global options work for BTooltip component but not directive

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#2076]
### Describe the bug

Looks like global options work for the BTooltip component but not directive. Internally both use BPopover, but via the directive  it can't inject the global option, it's always empty.

### Reproduction

https://github.com/dword-design-honestly/demo-bootstrap-vue-next-tooltip-directive-global-options

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dwgray** [comment]
Weirdly, I ran into a related issue yesterday: Which was that `useId` was not finding my injected `getId` when rendering a popover via the `v-b-tooltip` directive.

It think this issue https://github.com/vuejs/vue/issues/6487 is relevant. There is a potential workaround near the bottom of the thread - https://github.com/vuejs/vue/issues/6487#issuecomment-1591733289  - but even if that works, it's a solution for directly accessing provided values from the directive. If we go that route, the directives would have to pass the values to the composables (`useId` in the case I was looking at or `useDefaults` in your case).

I'd prefer to get access to the context from the composable, but I don't see any obvious way to do that. My lack of depth in vue.js may be showing here.

@VividLemon or @xvaara any thoughts on this?

**Comment by dword-design-honestly** [comment]
@dwgray Thanks a lot for replying! I'm not that deep into it, can you maybe provide a quick snippet on how to quickfix it for my case if possible? That would help me a lot 🙂.

**Comment by dwgray** [comment]
@dword-design-honestly I can't think of a way to work around this for your case. In my case I was just using the tooltip directive in a few places and I passed down an explicit id so that useId didn't go down the path of trying to inject a getId. I don't htink that applies for you - you would need a way to supply useDefaults with the values that you're providing. Maybe there is an alternate way to do those provides that is accesible to useDefaults without changing the code, but I doubt it.

I did a little more digging in the hope that I could at least get a proof of concept for the useId case running, but ran out of time.

The line `console.log((vnode as any).ctx.provides[idPluginKey])` does in fact return `() => (currentId++).toString().padStart(4, "0")` which is the test `getId` that I provided. So I think I could get something to work going down this path, but I'm hesitant to spend to much time on it, since `ctx` is undocumented and probably not something that we want to depend on.

I also saw that the binding paremeter that is sent into the mounting hook contains an [instance](https://vuejs.org/api/component-instance.html), which is the component that the directive is being injected into. This seems like a more reasonable path. The instance object has a documented ($options)[https://vuejs.org/api/options-composition] field that is supposed to have both provide and inject, but I'm not seeing either of those at runtime in my case, so I'm again stumped.

@VividLemon or @xvaara I'm interested both in how important you think this issue is and if you have any thoughts on a path to a solution if you think this should be fixed.

**Comment by VividLemon** [comment]
This isn't something that we can really fix. The directive itself is something that shouldn't really exist. It's very hacky

**Comment by VividLemon** [comment]
In a similar way to how the modal & toast orchestrators work, I suppose it could be possible to create a composable for this instead. The drawback being directives still wouldn't work, or would be better off deprecated ig

**Comment by dword-design-honestly** [comment]
That's interesting I didn't know that the directives aren't recommended. Maybe a quick note in the doc would prevent that case. I do like directives in general.

**Comment by xvaara** [comment]
@dword-design-honestly  usage of directives on components is not recomented, since directives are only for modifying dom, not for usage of vue functionality: https://vuejs.org/guide/reusability/custom-directives.html#usage-on-components

**Comment by dword-design-honestly** [comment]
Thanks!

**Comment by dword-design-honestly** [comment]
But not discouraged on native dom elements (e.g. span, svg, etc.).

**Comment by dwgray** [comment]
@dword-design-honestly it looks like @xvaara (mostly) fixed this with #2170.

The limitations, as I understand them, are that we're directly merging the default properties at the level of the directive, so we're explicitly grabbing the `BTooltip` defaults in the tooltip directive. This means that for your case, you would have to set the defaults for `BTooltip` explicitly, rather than depending on the `BPopover` defaults. It also doesn't work for any props that are explicitly bound via the directive props. e.g. it works for `noFade` as in your example, but wouldn't work for `placement`.

@xvaara - The reason I noticed this is that I was looking at how vuetify solved this problem. Both from the technical perspective and the DX perspective (do they use directives in a similar way?). It turns out they do have a tooltip directive quite similar to ours, but they solve the provides issue in what I think is a more general way. If I'm reading the code correctly, it doesn't have the limitations that I enumerated above. If you look at their `mountComponent` function in [directiveComponents.ts](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/directiveComponent.ts#L81), rather than extracting defaults from the provides, they add provides to the appcontext for the node that they're binding.

This is stretching my knowledge of how Vue works, but if you agree that vuetify's approach looks like it could improve how our directives work, I'd be willing to take a run at implementing it in our system.

**Comment by VividLemon** [comment]
Also this https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/composables/useTooltip/index.ts but I never wrote any docs and don't know if it works

@xvaara If this issue is finished, please close
