### ISSUE TITLE
BBadge incorrectly declares bg-variant and text-variant properties

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#2122]
### Describe the bug

I'm pretty sure the bootstrap badge component doesn't respect the `text-*` and `bg-*` classes (see the reproduction below). If I'm right, we shouldn't be exposing the `bg-variant` and `text-variant` properties. I think this means removing the us of `useColorVariantClasses` and manually implementing the handling of the `variant` property?

### Reproduction

https://stackblitz.com/edit/github-bserkl?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Not quite. This should be something written somewhere in the documentation among components with a default variant prop.

When you use prop variant, it will overwrite props textVariant & bgVariant. So when you have default props like BBadge's `variant: 'secondary'` you will only get `text-bg-secondary`

In order to get your 
`<BBadge text-variant="success" bg-variant="danger"> testing </BBadge>`
example to work, you would need to do
`<BBadge text-variant="success" bg-variant="danger" :variant="null"> testing </BBadge>`

There isn't a great way to fix this manually for users, I think the best is to just have some resource that tells why it doesn't work. BAvatar should suffer from the same issue

**Comment by dwgray** [comment]
Thanks for the explanation. #2200 is my attempt to address this in documentation - and you're right `BAvatar` has a similar issue and there was a visible bug in the docs if you looked carefully enough. By my reading `BButton` also has this issue.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2200#issuecomment-2351273613
