### ISSUE TITLE
RFC: usage of useless text prop

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#2257]
Multiple components have a prop called text and this:
```vue
    <slot>
      {{ props.text }}
    </slot>
```

I find the prop text to be useless and we could remove it. Thoughts?

**Comment by VividLemon** [comment]
One such issue is that composable controllers will have to essentially always use render functions

**Comment by VividLemon** [comment]
I'd say no to this because of 

1. It simplifies composable controllers since there is no way to really pass things to the slots unless you're using component: h()
2. By using the props with `useDefaults` you can globally set text on some component. Why you'd want to do this idk
3. Syntactically it's shorter than having to write out `<template #text> {{ text }} </template>` when you can just do `:text`

I'd agree that it could reduce duplication, and if I didn't see the value in the above I'd prefer to just use defineSlots and make the slots required. But I think there are good usages of the props, even if it's just #3

**Comment by xvaara** [comment]
> I'd say no to this because of
> 
> 1. It simplifies composable controllers since there is no way to really pass things to the slots unless you're using component: h()

you mean in the loop in the orchestrators?
```vue
<component ... v-for="[self, modal] ... >
 <template v-for="s in modal.slots" v-slot[s.name]>{{s.content}}</template>
</component>
```
or something like that.

> 2. By using the props with `useDefaults` you can globally set text on some component. Why you'd want to do this idk

weird 😅

> 3. Syntactically it's shorter than having to write out `<template #text> {{ text }} </template>` when you can just do `:text`

most of them are default slot, so its `<BNavText :text="foo" />` vs `<BNavText>foo</BnavText>`

> I'd agree that it could reduce duplication, and if I didn't see the value in the above I'd prefer to just use defineSlots and make the slots required. But I think there are good usages of the props, even if it's just `#3`

**Comment by VividLemon** [comment]
In my super-executive position, I say that the props syntax stays
