### ISSUE TITLE
Refactor: consistent composable for show/hide, composable for managing lazy states, add prop back for "visible"

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#2283]
Hey, part of the rewrite for show/hide PR I got to think about those props.

They don't all work the same way, so I'd like to define how they should work, so that I can make all them coherent.

My proposal:
1. If modelValue is true, we animete the element in. (of course no animation if that prop is set)
2. toggle is true -> in onMount we set modelValue to true and animate
3. visible is true -> we set modelValue true and display the component without animation (as it would have been open already)

visible takes priority over toggle. Both props are reactive and act as described when changed.

@VividLemon @dwgray thoughts? few of the components (collapse ie) already work like this.

**Comment by VividLemon** [comment]
Also the props are fine ideas. There are some bootstrap-vue components that use similar sounding props, to where it's essentially `:model-value="true"`, I removed them because it was like a second way to show an element, but I'm warming up to the idea of including them as static props. I don't remember which components in BV use them, or if they're even called the same thing consistently. I recall some of these props are name-dropped in the migration guide, which would need to be updated
