### ISSUE TITLE
B-Table composite Column

### ISSUE THREAD

**Issue by inndividuell** [bootstrap-vue-next/bootstrap-vue-next#248]
Hello,
in Vue 2 the b-table allowed sth like this:
`
      <template #cell(nameage)="data">
        {{ data.item.name.first }} is {{ data.item.age }} years old
      </template>`
But in this extension I don't get the values of the current item.
I get the value of the cell if this exists and all items. 
data.items for example delivers here all items in the table.

so you could go for data.items[0] but you dont have the index right?

Has anybody a solution for this problem. I want to access other columns values from the same row.

Thank you

**Comment by protomors** [comment]
"item" and "index" properties are already implemented. But they are not in the latest release yet. If you add bootstrap-vue-3@develop as dependency to your project, instead of bootstrap-vue-3@latest they will be available.
Keep in mind that B-table conponent is still not fully implemented (no sorting or filtering).

**Comment by cdmoro** [comment]
I've just published a new version: 0.1.0. This issue should have been solved by now, please let me know when you test it.
