### ISSUE TITLE
SortCompare Added for BTable

### ISSUE THREAD

**Issue by alexdohm** [bootstrap-vue-next/bootstrap-vue-next#694]
Thank you so much for adding sorting to the tables! I was reading your current code, and noticed that there is not yet the ability to do sort-compare routines with columns. I was wondering if this was already on the agenda, and if not, would it be possible to implement?

https://bootstrap-vue.org/docs/components/table#custom-sort-compare-routine

**Comment by devhus** [comment]
Sure, why not? 😄

**Comment by alexdohm** [comment]
On this same note, a custom filter function would also be great!

**Comment by devhus** [comment]
> On this same note, a custom filter function would also be great!

After thinking about it, I am not quite sure a custom filter function is really needed since you can already filter the items through the ``provider`` prop which is the alternative option for https://bootstrap-vue.org/docs/components/table#using-items-provider-functions
Note that you could also sort the items through the provider but, I've added ``sort-compare`` prop as an exception since sorting is way too simple to go through using a provider function for it.

Let me know what you think and i might implement it if it is important, Other than that, I don't think we should through too much logic to the component to keep it as small and as simple as possible.

**Comment by VividLemon** [comment]
Related: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1676
