### ISSUE TITLE
BFormFile

### ISSUE THREAD

**Issue by pablobbb** [bootstrap-vue-next/bootstrap-vue-next#752]
Hi everyone!
Just a question... is the BFormFile under development/planned or it won't be implemented?

Thanks

**Comment by VividLemon** [comment]
It is not being made currently. But at some point in the future it will be. Likely not the near future.

**Comment by dagnelies** [comment]
That would be great, I'm in the need for that too. +1 vote for the priority list ;)

**Comment by tak-ho-raspect** [comment]
+1 here too

**Comment by VividLemon** [comment]
I'm not trying to stomp on your hopes and dreams, but implementing a custom component is not as important to me as getting Nuxt3 support ready, and finishing code coverage. Among some other high priority issues, like fixing the currently broken BToast component. If you're interested though, it may be fairly simple to pull a custom component in from bootstrap-vue. If anyone would like, I can explain the process for implementing.

**Comment by tak-ho-raspect** [comment]
@VividLemon then let me try to copy the BFile component from bootstrap-vue and transform it to composition style, I hope it is simple. Thanks!

**Comment by dagnelies** [comment]
> [...] implementing a custom component is not as important to me as getting Nuxt3 support ready, and finishing code coverage.

Hi, no problem, it's your priorities. However, from a library user's perspective, I'd like to emphasize that the order is reversed.

1. it *MUST* work
   - breaking the whole app just by importing a component is a no-go, it's better to remove the component as a whole if it just breaks the whole app and does not work anyway. 
3. it *SHOULD* have enough features
   - currently it's missing so much, or is buggy, that it's barely usable. It's misleading to showcase all these components because many of them are broken or buggy
5. having good test coverage is a *NICE* to have
   - from a user's perspective irrelevant, it is more important to since the thing should first be working properly

I do not mean to bash you. It's just that using this lib currently leads to unpleasant surprises because of the bugs, missing stuff and rough edges, so rethinking the priorities might be useful. By this, I don't mean that this toast must become the first prio. I mean that things should be clearly communicated and indicated in the docs by marking all buggy components as "alpha" for example. It's very time consuming as a user to try using something just to end up in debugging sessions and discover in the end that the component itself is actually bonkers. If it's labelled as "alpha", at least you know what you are getting into.

**Comment by tak-ho** [comment]
No I am sorry, I switch to vuetify eventually...

**Comment by Trosmanx** [comment]
Hi, so it means, that in new version it will not be? How to input files now with usage of bootstrap next?

**Comment by VividLemon** [comment]
The implementation is somewhat different than the bootstrap-vue implementation. You will likely want to read the documentation https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-file.html

**Comment by therecluse26** [comment]
@VividLemon The docs say "The implementation may change to become closer to the Bootstrap-vue implementation based on feedback." I'd imagine this should go without saying, as you'd ideally want to minimize the amount of breaking changes involved in upgrading, and the project is called bootstrap-vue-next.
